# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Cl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Clients(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsClients(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Clients()
        x.Init(buf, n + offset)
        return x

    # Clients
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Clients
    def Clients(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cl.Client import Client
            obj = Client()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Clients
    def ClientsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Clients
    def ClientsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ClientsStart(builder): builder.StartObject(1)
def ClientsAddClients(builder, clients): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clients), 0)
def ClientsStartClientsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ClientsEnd(builder): return builder.EndObject()
